### ISSUE TITLE
coinbase format have changed for Convert Coinbase CSV to TurboTax Format

### ISSUE THREAD

**Issue by mukeshsingh2016** [ClaireDuSoleil/ClaireDuSoleil.github.io#5]
Below is correct header and value

Transaction Type	Transaction ID	Tax lot ID	Asset name	Amount	Date Acquired	Cost basis (USD)	Date of Disposition	Proceeds (USD)	Gains (Losses) (USD)	Holding period (Days)	Data source

Trade	95c5a11f-25ba-5039-891f-a062d11b5e65	e93f352e-07d1-413d-9a51-8a09dbbbb45f	ETH	2.53908249	2/19/2021	5000	3/31/2021	4835.441389	-164.5586106	40	Coinbase

**Comment by ClaireDuSoleil** [comment]
Coinbase can generate different histories as a CSV.  This webpage assumes you generated the report using this method:

1. Login to your Coinbase account
2. Click on your profile picture (or blank user picture) in upper-right corner and select "Reports" 
3. Select "**Transaction History**" and "**Generate Report**"

Do not select the reports in the taxes section for use with this webpage since it won't work.

I hope this helps.  
Thank you,
Claire

**Comment by mukeshsingh2016** [comment]
Hi Claire, 

Thank you for quick response. I really appreciated. After following your instruction. I am again stuck.    
I am getting error as ERROR: Not enough ALGO banked to cover sale on 2021-04-03T12:58:02Z. There are few more rows with same issue. Can you please check your logic for this calc.

Timestamp | Transaction Type | Asset | Quantity Transacted | Spot Price Currency | Spot Price at Transaction | Subtotal | Total (inclusive of fees) | Fees | Notes
2021-04-03T12:58:02Z | Sell | ALGO | 9497.746 | USD | 1.43 | 13600 | 13397.36 | 202.64 | Sold 9497.745958 ALGO for $13397.36 USD

Thanks
Mukesh

**Comment by mukeshsingh2016** [comment]
> Coinbase can generate different histories as a CSV. This webpage assumes you generated the report using this method:
> 
> 1. Login to your Coinbase account
> 2. Click on your profile picture (or blank user picture) in upper-right corner and select "Reports"
> 3. Select "**Transaction History**" and "**Generate Report**"
> 
> Do not select the reports in the taxes section for use with this webpage since it won't work.
> 
> I hope this helps. Thank you, Claire

Hi Claire,

Thank you for quick response. I really appreciated. After following your instruction. I am again stuck.
I am getting error as ERROR: Not enough ALGO banked to cover sale on 2021-04-03T12:58:02Z. There are few more rows with same issue. Can you please check your logic for this calc.

Timestamp | Transaction Type | Asset | Quantity Transacted | Spot Price Currency | Spot Price at Transaction | Subtotal | Total (inclusive of fees) | Fees | Notes
2021-04-03T12:58:02Z | Sell | ALGO | 9497.746 | USD | 1.43 | 13600 | 13397.36 | 202.64 | Sold 9497.745958 ALGO for $13397.36 USD

Thanks
Mukesh

**Comment by ClaireDuSoleil** [comment]
Hi Mukesh, 

I will examine my logic again with sales.  Rounding errors gave me a lot of headaches last year but I was hoping those were now fixed.  Coinbase also rounds their values in the CSV and that may introduce errors.  In any case, there are two possible issues that I can see right now:

When you generate a Coinbase transaction history, you must select "All Time".  If you only selected 2021 when you generated the Coinbase report then if you sold ALGO in 2021 but purchased it in 2020 then the code will flag an error because the report you supplied has no record of 2020 purchases.  If you only want my webpage to generate a proceeds CSV for 2021 then, after you load the **full** CSV from Coinbase, apply the filter using the dropdown underneath the table that gets produced.  It says "Filter By Year" and then apply filter.

The other possibility is that I still have rounding errors in my code.  Since my own CSV from Coinbase is working, this might be difficult to fix without an example CSV that causes the problem.  In any case, I have modified the error message to display the amount that is missing, such as 

> ERROR: Not enough BTC banked to cover sale on 2021-12-27T17:55:56Z  Balance available for BTC is 0.000000060000

If you see this error printing out an extremely low available balance, which equates to less than .01 $ in value, then there are rounding problems. If your problem is due to rounding errors and not missing **Buy** transactions, then I will modify the code to ignore the errors and keep going if the value of the missing asset balance is worth less than .01 dollars.

Thank you,
Claire

**Comment by ClaireDuSoleil** [comment]
I just modified the error alert dialog to make a bit more sense.  It will look like this:

> ERROR: Not enough BTC banked to cover sale on 2021-12-27T17:55:56Z  Still need  BTC balance of  0.000000060000

If the dollar value of this balance is less than $0.01 then I can modify the code to ignore and go on.

**Comment by mukeshsingh2016** [comment]
> I just modified the error alert dialog to make a bit more sense. It will look like this:
> 
> > ERROR: Not enough BTC banked to cover sale on 2021-12-27T17:55:56Z  Still need  BTC balance of  0.000000060000
> 
> If the dollar value of this balance is less than $0.01 then I can modify the code to ignore and go on.


My all transactions are from  2021 only. ERROR: Not enough ALGO banked to cover sale on 2021-04-03T12:58:02Z  Balance available for ALGO is 9029.169410000000. 

for below transaction

Timestamp | Transaction Type | Asset | Quantity Transacted | Spot Price Currency | Spot Price at Transaction | Subtotal | Total (inclusive of fees) | Fees | Notes
2021-04-03T12:58:02Z | Sell | ALGO | 9497.746 | USD | 1.43 | 13600 | 13397.36 | 202.64 | Sold 9497.745958 ALGO for $13397.36 USD

**Comment by mukeshsingh2016** [comment]
My all transactions are from 2021 only. ERROR: Not enough ALGO banked to cover sale on 2021-04-03T12:58:02Z Balance available for ALGO is 9029.169410000000.

for below transaction

Timestamp | Transaction Type | Asset | Quantity Transacted | Spot Price Currency | Spot Price at Transaction | Subtotal | Total (inclusive of fees) | Fees | Notes
2021-04-03T12:58:02Z | Sell | ALGO | 9497.746 | USD | 1.43 | 13600 | 13397.36 | 202.64 | Sold 9497.745958 ALGO for $13397.36 USD

**Comment by mukeshsingh2016** [comment]
> My all transactions are from 2021 only. ERROR: Not enough ALGO banked to cover sale on 2021-04-03T12:58:02Z Balance available for ALGO is 9029.169410000000.
> 
> for below transaction
> 
> Timestamp | Transaction Type | Asset | Quantity Transacted | Spot Price Currency | Spot Price at Transaction | Subtotal | Total (inclusive of fees) | Fees | Notes 2021-04-03T12:58:02Z | Sell | ALGO | 9497.746 | USD | 1.43 | 13600 | 13397.36 | 202.64 | Sold 9497.745958 ALGO for $13397.36 USD

[Coinbase-602854f95d022f06ea02147b-TransactionsHistoryReport-2022-03-27-18_09_59.csv](https://github.com/ClaireDuSoleil/ClaireDuSoleil.github.io/files/8358208/Coinbase-602854f95d022f06ea02147b-TransactionsHistoryReport-2022-03-27-18_09_59.csv)

**Comment by ClaireDuSoleil** [comment]
Thank you for the example CSV.  I can reproduce the problem and I will let you know what I find.  I think it has something to do with the conversions.

Thank you,
Claire

**Comment by mukeshsingh2016** [comment]
> Thank you for the example CSV. I can reproduce the problem and I will let you know what I find. I think it has something to do with the conversions.
> 
> Thank you, Claire

Please download, I am going to delete this csv.

Thanks
Mukesh

**Comment by ClaireDuSoleil** [comment]
I have it now--you can delete.

**Comment by mukeshsingh2016** [comment]
> I have it now--you can delete.

Thank you. Please let me know once you fixed this issue. I tax work is pending because of csv to TXF conversion. Thank you time and help.

Thanks
Mukesh

**Comment by ClaireDuSoleil** [comment]
Hi Mukesh,

I've fixed two issues.  One was with a comma being in the notes field of a conversion that I wasn't expecting.  This was causing a value of "9,163.278225 ALGO" to only be 9.  The other issue was the rounding which I fixed with an adjustment.  If you know how to open the developer console, you can see lots of messages.  Whenever I modify the transaction quantity to adjust for rounding, you will see a message like:

> rounding adjustment for ALGO diff=0.000003000000 setting runningQuantity to 12.452197 from 12.452194

Please let me know if this works for you.  Thank you for the CSV.  I could not have found the comma problem without it.  My conversions were always too small to see that issue.

Claire

**Comment by mukeshsingh2016** [comment]
> Hi Mukesh,
> 
> I've fixed two issues. One was with a comma being in the notes field of a conversion that I wasn't expecting. This was causing a value of "9,163.278225 ALGO" to only be 9. The other issue was the rounding which I fixed with an adjustment. If you know how to open the developer console, you can see lots of messages. Whenever I modify the transaction quantity to adjust for rounding, you will see a message like:
> 
> > rounding adjustment for ALGO diff=0.000003000000 setting runningQuantity to 12.452197 from 12.452194
> 
> Please let me know if this works for you. Thank you for the CSV. I could not have found the comma problem without it. My conversions were always too small to see that issue.
> 
> Claire

Thank you so much Claire. Yes. It is working as excepted. Thank you working on weekend and getting this fix.
